application: toooodoooos
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /archiveall
  login: admin
  script: main.cron
- url: /.*
  script: main.app